
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Ext_congtyScalarFieldEnum = {
  id: 'id',
  mst: 'mst',
  ten: 'ten',
  tenVietTat: 'tenVietTat',
  diaChi: 'diaChi',
  dienThoai: 'dienThoai',
  email: 'email',
  nguoiDaiDien: 'nguoiDaiDien',
  isActive: 'isActive',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_listhoadonScalarFieldEnum = {
  id: 'id',
  idServer: 'idServer',
  brandname: 'brandname',
  congtyId: 'congtyId',
  nbmst: 'nbmst',
  nbten: 'nbten',
  nbdchi: 'nbdchi',
  nmmst: 'nmmst',
  nmten: 'nmten',
  nmdchi: 'nmdchi',
  khmshdon: 'khmshdon',
  khhdon: 'khhdon',
  shdon: 'shdon',
  mhso: 'mhso',
  tgtcthue: 'tgtcthue',
  tgtthue: 'tgtthue',
  tgtttbso: 'tgtttbso',
  tdlap: 'tdlap',
  tthai: 'tthai',
  loaihd: 'loaihd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_detailhoadonScalarFieldEnum = {
  id: 'id',
  idServer: 'idServer',
  idhdonServer: 'idhdonServer',
  stt: 'stt',
  ten: 'ten',
  dvtinh: 'dvtinh',
  sluong: 'sluong',
  dgia: 'dgia',
  thtien: 'thtien',
  tsuat: 'tsuat',
  tthue: 'tthue',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_sanphamhoadonScalarFieldEnum = {
  id: 'id',
  iddetailhoadon: 'iddetailhoadon',
  ten: 'ten',
  ten2: 'ten2',
  ma: 'ma',
  dvt: 'dvt',
  dgia: 'dgia',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_apiconfigScalarFieldEnum = {
  id: 'id',
  name: 'name',
  congtyId: 'congtyId',
  bearerToken: 'bearerToken',
  baseUrl: 'baseUrl',
  brandname: 'brandname',
  batchSize: 'batchSize',
  delayBetweenBatches: 'delayBetweenBatches',
  delayBetweenDetailCalls: 'delayBetweenDetailCalls',
  maxRetries: 'maxRetries',
  lastSyncAt: 'lastSyncAt',
  lastSyncStatus: 'lastSyncStatus',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_synclogScalarFieldEnum = {
  id: 'id',
  congtyId: 'congtyId',
  configId: 'configId',
  syncType: 'syncType',
  fromDate: 'fromDate',
  toDate: 'toDate',
  totalRecords: 'totalRecords',
  successCount: 'successCount',
  errorCount: 'errorCount',
  status: 'status',
  errorMessage: 'errorMessage',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.Ext_tonghopScalarFieldEnum = {
  id: 'id',
  idDetailServer: 'idDetailServer',
  idHoadonServer: 'idHoadonServer',
  congtyId: 'congtyId',
  congtyMst: 'congtyMst',
  congtyTen: 'congtyTen',
  khmshdon: 'khmshdon',
  khhdon: 'khhdon',
  shdon: 'shdon',
  mhso: 'mhso',
  tdlap: 'tdlap',
  tthai: 'tthai',
  loaihd: 'loaihd',
  nbmst: 'nbmst',
  nbten: 'nbten',
  nbdchi: 'nbdchi',
  nmmst: 'nmmst',
  nmten: 'nmten',
  nmdchi: 'nmdchi',
  stt: 'stt',
  tenHang: 'tenHang',
  tenHangChuan: 'tenHangChuan',
  maHang: 'maHang',
  nhomHang: 'nhomHang',
  dvtinh: 'dvtinh',
  sluong: 'sluong',
  dgia: 'dgia',
  thtien: 'thtien',
  tsuat: 'tsuat',
  tthue: 'tthue',
  tongTien: 'tongTien',
  soLuongNhap: 'soLuongNhap',
  soLuongXuat: 'soLuongXuat',
  giaTriNhap: 'giaTriNhap',
  giaTriXuat: 'giaTriXuat',
  searchText: 'searchText',
  tags: 'tags',
  nam: 'nam',
  thang: 'thang',
  quy: 'quy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  syncedAt: 'syncedAt'
};

exports.Prisma.Ext_sanpham_dictionaryScalarFieldEnum = {
  id: 'id',
  tenGoc: 'tenGoc',
  tenChuan: 'tenChuan',
  maHang: 'maHang',
  nhomHang: 'nhomHang',
  dvtinh: 'dvtinh',
  congtyId: 'congtyId',
  frequency: 'frequency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_daily_stock_v2ScalarFieldEnum = {
  id: 'id',
  congtyId: 'congtyId',
  date: 'date',
  tenHangChuan: 'tenHangChuan',
  maHang: 'maHang',
  dvtinh: 'dvtinh',
  tonDauQty: 'tonDauQty',
  tonDauVal: 'tonDauVal',
  nhapQty: 'nhapQty',
  nhapVal: 'nhapVal',
  xuatQty: 'xuatQty',
  xuatVal: 'xuatVal',
  tonCuoiQty: 'tonCuoiQty',
  tonCuoiVal: 'tonCuoiVal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Ext_mapping_queueScalarFieldEnum = {
  id: 'id',
  tenGoc: 'tenGoc',
  dvtGoc: 'dvtGoc',
  aiSuggestedName: 'aiSuggestedName',
  aiConfidence: 'aiConfidence',
  aiReasoning: 'aiReasoning',
  status: 'status',
  congtyId: 'congtyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  ext_congty: 'ext_congty',
  ext_listhoadon: 'ext_listhoadon',
  ext_detailhoadon: 'ext_detailhoadon',
  ext_sanphamhoadon: 'ext_sanphamhoadon',
  ext_apiconfig: 'ext_apiconfig',
  ext_synclog: 'ext_synclog',
  ext_tonghop: 'ext_tonghop',
  ext_sanpham_dictionary: 'ext_sanpham_dictionary',
  ext_daily_stock_v2: 'ext_daily_stock_v2',
  ext_mapping_queue: 'ext_mapping_queue'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
